#!/bin/bash

xsettingsd &
xcompmgr &
xscreensaver &

volumeicon &
/usr/share/goobuntu-indicator/goobuntu_indicator.py &

if [ "z$DISPLAY" = "z:0" ]; then
  xscreensaver &
else
  . $HOME/.profile
fi

xrandr --output DisplayPort-1 --auto --left-of DisplayPort-0 --output DisplayPort-0 --auto

exec xmonad
